web/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.urls')),
]

web/src/urls.py
from django.urls import path
from . import views

app_name = 'src'

urlpatterns = [
    path('', views.index, name='index'),
    path('agents', views.view_agents, name='agents'),
    path('agents/<int:id>/edit', views.edit_agent, name='edit_agent'),
    path('agents/<int:id>/edit/delete', views.del_agent, name='del_agent'),
]

web/src/models.py
from django.db import models
from django.forms import ModelForm, TextInput
from django.contrib.admin import widgets

# Create your models here.
class Role(models.Model):
    role = models.CharField(max_length=10)

    def __str__(self):
        return self.role

class Agent(models.Model):
    is_available = models.BooleanField(default=False)
    available_since = models.TimeField(blank=True, null=True)
    roles = models.ManyToManyField(Role)

    def __str__(self):
        return str(self.id)

class Agent_Form(ModelForm):
    class Meta:
        model = Agent
        fields = '__all__'
        widgets = {
            'available_since': TextInput(attrs={'placeholder': 'hr:min (24 hr)'})
        }
    
MODES = (
    ("available","available"), ("least_busy","least_busy"), ("random","random")
)

class Issue(models.Model):
    roles = models.ManyToManyField(Role)
    mode = models.CharField(choices=MODES, max_length=12)

    def __str__(self):
        return str(self.id)

class Issue_Form(ModelForm):
    class Meta:
        model = Issue
        fields = '__all__'  

web/src/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Max, Min
import random

# Create your views here.
def index(request):
    if request.method == "POST":
        form = Issue_Form(request.POST)
        if form.is_valid():
            mode = form.cleaned_data['mode']
            roles = form.cleaned_data['roles']
            agents = Agent.objects.filter(is_available=True,roles__in=roles).distinct()
            max_id = agents.aggregate(max_id=Max("id"))['max_id']
            min_id = agents.aggregate(min_id=Min("id"))['min_id']
            pk = random.randint(min_id, max_id)

            if mode == "random":
                return render(request,'src/index.html',{
                    'form': Issue_Form(), 'agents': Agent.objects.get(pk=pk),'mode':mode, 'roles':roles
                }) 

            elif mode == "available":    
                return render(request,'src/index.html',{
                        'form': Issue_Form(), 'agents':agents, 'available':True,'mode':mode, 'roles':roles
                    })
            
            return render(request,'src/index.html',{
                        'form': Issue_Form(), 'agents':agents.earliest('available_since'),'mode':mode, 'roles':roles
                    })

        else:
            return redirect('src:index')

    return render(request,'src/index.html',{
        'form': Issue_Form()
    })

def view_agents(request):
    if request.method == "POST":
        form = Agent_Form(request.POST)
        if form.is_valid():
            form.save()
            return redirect('src:agents')

    return render(request, 'src/agents.html',{
        'form':Agent_Form(), 'agents': Agent.objects.all()
    })


def edit_agent(request, id):
    agent = Agent.objects.get(pk=id)
    form = Agent_Form(instance=agent)

    if request.method == 'POST':
        update_form = Agent_Form(request.POST, instance=agent)
        if update_form.is_valid():
            update_form.save()
            return redirect('src:agents')
    
    return render(request,'src/edit_agent.html',{
        'form': form, 'agent':agent
    })

def del_agent(request, id):
    agent = Agent.objects.get(pk=id)
    agent.delete()
    return redirect('src:agents')

web/src/templates/src/agents.html
{% extends 'src/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Agents{% endblock title %}
{% block title_1 %}Agents{% endblock title_1 %}
{% block title_2 %}Home{% endblock title_2 %}
{% block url %}{% url 'src:index' %}{% endblock url %}

{% block body %}
    <div class="container-fluid"></div>
        <div align='center'>
            <h2>Create new Agent</h2>
            <div class="container d-flex h-100 row justify-content-center col-20">
                <form align='center' method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success my-2" type="submit" value="Create Agent">
                </form>
            </div>
        </div>
        <div id="agents">
            <h1 align="center" class="my-2">Agents present in Database</h1>
            <div class="row">
                {% for agent in agents %}
    
                <div class="card my-3 mx-5 col-sm-3">
                    <h3 class="card-header">{{ agent }}</h3>
                    <div class="card-body">

                        <h6 class="card-subtitle mb-2 text-muted">
                            Status : {% if agent.is_available  %}
                                        Available
                                    {% else %}
                                        Not Available
                                    {% endif %}
                            <br>
                        </h6>
                        <p class="card-text">
                            Role(s) :
                            {% for r in agent.roles.all %}
                                {{ r }},
                            {% endfor %}
                            <br>
                            Available Since : {{ agent.available_since }}
                        </p>
                        <a href="{% url 'src:edit_agent' agent.id %}" class="card-link btn btn-info">Edit</a>
                    </div>
                </div>

                {% empty %}
                <h3>No agents</h3>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock body %}

web/src/templates/src/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %}{% endblock title %}</title>
</head>

<body>
    <nav class="navbar bg-dark navbar-dark">
        <a class="navbar-brand" href="#">{% block title_1 %}{% endblock title_1 %}</a>
        <a href={% block url %}{% endblock url %} class="btn btn-light" text-align='center'>{% block title_2 %}{% endblock title_2 %}</a>
    </nav>

    {% block body %}{% endblock body %}
</body>
</html>

web/src/templates/src/edit_agent.html
{% extends 'src/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Edit agent{% endblock title %}
{% block title_1 %}Edit Agent{% endblock title_1 %}
{% block title_2 %}Cancel{% endblock title_2 %}
{% block url %}{% url 'src:agents' %}{% endblock url %}

{% block body %}
    <div align='center' class="container-fluid">
        <h2>ID : {{ agent }}</h2>
        <div class="container d-flex h-100 row justify-content-center col-50">
            <form align="center" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input class="btn btn-info my-3" type="submit" value="Update">
            </form>
        </div>
        <a href="{% url 'src:del_agent' agent.id %}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this agent?')">Delete</a>
    </div>
{% endblock body %}

web/src/templates/src/index.html
{% extends 'src/base.html' %}

{% load crispy_forms_tags %}

{% block title %}Home{% endblock title %}
{% block title_1 %}Welcome{% endblock title_1 %}
{% block title_2 %}View agents{% endblock title_2 %}
{% block url %}{% url 'src:agents' %}{% endblock url %}

{% block body %}
    <div class="container-fluid">
        <div align='center'>
            <h2>Enter Issue details</h2>
            <div class="container d-flex h-100 row justify-content-center col-20">
                <form align='center' method="POST">
                    {% csrf_token %}
                    {{ form|crispy }}
                    <input class="btn btn-success my-3" type="submit" value="View Agents">
                </form>
            </div>
        </div>
        {% if agents %}
            <div id="issue" align="center" class="my-2">
                <h5>
                    Mode selected : {{ mode }}<br>
                    Role(s) :
                    {% for r in roles %}
                        {{ r }},
                    {% endfor %}
                </h5>
            </div>
            <br>
            <div id="agents" align="center" class="my-2">
                <h3>ID of agent(s) for the issue :</h3>
                {% if available %}
                <ul>
                    {% for a in agents %}
                        <li>
                            {{ a }}
                        </li>                      
                        {% empty %}
                        <h4>No agents available</h4>
                    {% endfor %}
                </ul>
                {% else %}
                <h4>{{ agents }}</h4>
                {% endif %}
            </div>
        {% endif %}
    </div>
{% endblock body %}